# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: tensorflow
  version: 2.3.1

about:
  home: https://tensorflow.org
  license: Apache License
  summary: 'TensorFlow 2.3.1 conda package based on the PyPI wheels.

  Also includes numpy 1.18.1, h5py 2.10 and opencv-python-headless 4.2.0.34.

  For GPU support, install cudatoolkit 10.1 and cudnn 7.6 which are available as conda packages on the default channel.'

build:
  number: 2.3.1

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'

  host:
    - python=3.6
    - pip

  run:
    - python=3.6
    - pip
    # - cudatoolkit=10.1
    # - cudnn=7.6

test:
  imports:
    - tensorflow
    - numpy
    - h5py
    - cv2